# Generated by Django 4.2.5 on 2023-10-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='position',
            field=models.CharField(default='No position specified', max_length=3),
        ),
    ]
